#### Clustering Wikipedia Articles
In this analysis, I'll use `TruncatedSVD` to perform Principle Component Analysis on sparse arrays in `csr_matrix` format--in this case word-frequency arrays. First, I'll build the necessary machine learning pipeline using `TruncatedSVD` and k-means to cluster some popular pages from Wikipedia. Then, I'll apply it to the word-frequency array of some popular Wikipedia articles.

The data are available from [Lateral.io](https://blog.lateral.io/2015/06/the-unknown-perils-of-mining-wikipedia/)

In [29]:
# Perform the necessary imports
import pandas as pd
import numpy as np

from sklearn.decomposition import TruncatedSVD
from sklearn.cluster import KMeans
from sklearn.pipeline import make_pipeline
from scipy.sparse import csr_matrix

In [30]:
# Read in the Wikipedia articles as a dataframe
df = pd.read_csv('datasets/wikipedia-vectors.csv', index_col=0)

# Transpose the dataframe otherwise there will be 13,000 columns (corresponding to the 13,000 words in the file)
articles = csr_matrix(df.transpose())
titles = list(df.columns)

In [31]:
# Create a TruncatedSVD instance
svd = TruncatedSVD(n_components=50)

# Create a KMeans instance
kmeans = KMeans(n_clusters=6)

# Create a pipeline
pipeline = make_pipeline(svd, kmeans)

# Fit the pipeline to articles
pipeline.fit(articles)

# Calculate the cluster labels
labels = pipeline.predict(articles)

# Create a DataFrame aligning labels and titles
df = pd.DataFrame({'label': labels, 'article': titles})

# Display df sorted by cluster label
print(df.sort_values('label'))

                                          article  label
29                               Jennifer Aniston      0
28                                  Anne Hathaway      0
27                                 Dakota Fanning      0
26                                     Mila Kunis      0
25                                  Russell Crowe      0
24                                   Jessica Biel      0
23                           Catherine Zeta-Jones      0
22                              Denzel Washington      0
21                             Michael Fassbender      0
20                                 Angelina Jolie      0
19  2007 United Nations Climate Change Conference      1
18  2010 United Nations Climate Change Conference      1
16                                        350.org      1
15                                 Kyoto Protocol      1
17  Greenhouse gas emissions by the United States      1
13                               Connie Hedegaard      1
12                             

#### Discovering interpretable features
As you can see, the above articles cluster into well determinable clusters. We have a topic that looks like 'internet technologies', and another for 'football', and another for 'actors', etc.

In the following, I'll employ a dimension reduction technique called "Non-negative matrix factorization" (NMF) that expresses samples as combinations of interpretable parts. For example, it expresses documents as combinations of topics. To apply NMF, I'll use the tf-idf word-frequency array of Wikipedia articles that I created earlier, given as a csr matrix. I'll fit the model and transform the articles, and then I'll explore the result.

In [32]:
# Import NMF
from sklearn.decomposition import NMF

# Create an NMF instance
model = NMF(n_components=6)

# Fit the model to articles
model.fit(articles)

# Transform the articles
nmf_features = model.transform(articles)

# Print the first 10 NMF features
print(nmf_features[0:10])

[[0.         0.         0.         0.         0.         0.44052876]
 [0.         0.         0.         0.         0.         0.56668499]
 [0.00382019 0.         0.         0.         0.         0.39870403]
 [0.         0.         0.         0.         0.         0.381795  ]
 [0.         0.         0.         0.         0.         0.48558457]
 [0.01292803 0.01378894 0.00776331 0.03344715 0.         0.33456931]
 [0.         0.         0.02067421 0.         0.00604557 0.35911324]
 [0.         0.         0.         0.         0.         0.49104488]
 [0.01542612 0.01428165 0.00376631 0.02371005 0.02626534 0.48084359]
 [0.01117295 0.03136769 0.03094882 0.06569705 0.01967034 0.33833672]]


In [33]:
# Create a pandas DataFrame
df = pd.DataFrame(nmf_features, index=titles)

# Print the row for 'Anne Hathaway'
print(df.loc['Anne Hathaway'])

# Print the row for 'Denzel Washington'
print(df.loc['Denzel Washington'])

0    0.003845
1    0.000000
2    0.000000
3    0.575686
4    0.000000
5    0.000000
Name: Anne Hathaway, dtype: float64
0    0.000000
1    0.005601
2    0.000000
3    0.422361
4    0.000000
5    0.000000
Name: Denzel Washington, dtype: float64


#### NMF features of the Wikipedia articles
When investigating the features above, notice that for both actors, the NMF feature 3 has by far the highest value. This means that both articles are reconstructed using mainly the 3rd NMF component. This is because NMF components represent topics (for instance, acting). When NMF is applied to documents, the components correspond to topics of documents, and the NMF features reconstruct the documents from the topics. 

Verifying this with the NMF model I have can be done. We saw above that the 3rd NMF feature value was high for articles about both actors Denzel Washington and Anne Hathaway. Now, I'll demonstrate how to identify the topic of the corresponding NMF component.

In [37]:
# Import the vocabulary csv and transform it into a list of words.
words_df = pd.read_csv('datasets/wikipedia-vocabulary.txt', header=None, names=['words'])
words = words_df.words.tolist()

# Create a DataFrame
components_df = pd.DataFrame(model.components_, columns=words)

# Print the shape of the DataFrame
print(components_df.shape)

# Select row 3 corresponding with the 3rd feature
component = components_df.iloc[3]

# call and print nlarges on component, this gives the five words with the highest values for that component.
print(component.nlargest())

(6, 13125)
film       0.627904
award      0.253143
starred    0.245295
role       0.211460
actress    0.186406
Name: 3, dtype: float64


#### NMF features are topics
It's now easy to recognise the topics that the articles about Anne Hathaway and Denzel Washington have in common! It certainly seems to make sense.

In [35]:
# Perform the necessary imports
import pandas as pd
from sklearn.preprocessing import normalize

# Normalize the NMF features
norm_features = normalize(nmf_features)

# Create a DataFrame
df = pd.DataFrame(norm_features, index=titles)

# Select the row corresponding to 'Cristiano Ronaldo'
article = df.loc["Cristiano Ronaldo"]

# Compute the dot products
similarities = df.dot(article)

# Display those with the largest cosine similarity
print(similarities.nlargest())

Cristiano Ronaldo                1.000000
Franck Ribéry                    0.999972
Radamel Falcao                   0.999942
Zlatan Ibrahimović               0.999942
France national football team    0.999923
dtype: float64


#### Conclusion Finding Similar Articles
Finally, I've quickly demonstrated how to use NMF features and the cosine similarity to find similar articles. I applied this to the NMF model for popular Wikipedia articles, by finding the articles most similar to the article about the footballer Cristiano Ronaldo. As you can see, we get back mostly other footballers and an article about a football team. Pretty cool! 